id: mode_presence_retour
alias: Retour maison
description: Restaure modes chauffage au retour
mode: single

trigger:
  - platform: state
    entity_id: zone.home
    from: "0"

action:
  - delay:
      minutes: 1

  - service: scene.turn_on
    target:
      entity_id: scene.avant_depart

  - service: persistent_notification.create
    data:
      title: Retour maison
      message: Modes restaures
