id: mode_presence_retour
alias: Mode Presence - Retour a la maison
description: Restaure les modes de chauffage sauvegardes lors du depart
mode: single

trigger:
  - platform: state
    entity_id: zone.home
    from: "0"

condition:
  - condition: numeric_state
    entity_id: zone.home
    above: 0

action:
  - delay:
      minutes: 2

  - condition: numeric_state
    entity_id: zone.home
    above: 0

  - service: scene.turn_on
    target:
      entity_id: scene.avant_depart
    continue_on_error: true

  - service: persistent_notification.create
    data:
      title: Retour detecte
      message: >
        Modes de chauffage restaures.
        Personnes: {{ states('zone.home') }}
