id: retour_presence
alias: Retour presence
mode: single

trigger:
  - platform: state
    entity_id: zone.home
    from: "0"

action:
  - service: scene.turn_on
    target:
      entity_id: scene.avant_depart
