# ========================================
# AUTOMATION DEPART/RETOUR
# ========================================
# Sauvegarde et restauration des modes lors depart/retour maison
# Note: Ce n'est PAS un "Mode Presence" modificateur
#       Juste sauvegarde/restauration simple
# ========================================

# AUTOMATION 1: DEPART
---
alias: Depart maison - Sauvegarde modes
description: Sauvegarde modes actuels et passe en Hors-Gel au depart
mode: single

triggers:
  - trigger: state
    entity_id:
      - zone.home
    to: "0"

conditions: []

actions:
  - action: scene.create
    metadata: {}
    data:
      scene_id: avant_depart
      snapshot_entities:
        - input_select.mode_chauffage_salon
        - input_select.mode_chauffage_cuisine

  - action: input_select.select_option
    target:
      entity_id: input_select.mode_chauffage_salon
    data:
      option: Hors-Gel(16)

  - action: input_select.select_option
    target:
      entity_id: input_select.mode_chauffage_cuisine
    data:
      option: Hors-Gel(16)

# ========================================

# AUTOMATION 2: RETOUR
---
alias: Retour maison - Restauration modes
description: Restaure modes sauvegardes au retour
mode: single

triggers:
  - trigger: state
    entity_id:
      - zone.home
    from: "0"

conditions: []

actions:
  - delay:
      hours: 0
      minutes: 1
      seconds: 0

  - action: scene.turn_on
    target:
      entity_id: scene.avant_depart
    metadata: {}
