alias: Chauffage - Mise à jour Mode Global
description: Change le mode global selon 4 créneaux horaires
mode: single

triggers:
  - at: "05:45:00"
    id: confort_matin
    trigger: time
  - at: "08:00:00"
    id: eco_journee
    trigger: time
  - at: "17:00:00"
    id: confort_soir
    trigger: time
  - at: "22:30:00"
    id: horsgel_nuit
    trigger: time

conditions:
  - condition: state
    entity_id: input_boolean.mode_vacance
    state: "off"

actions:
  - variables:
      target_temperature: |
        {% if trigger.id in ['confort_matin', 'confort_soir'] %}19
        {% elif trigger.id in ['eco_journee', 'horsgel_nuit'] %}17
        {% else %}18.5
        {% endif %}

  - action: input_number.set_value
    target:
      entity_id: input_number.mode_chauffage_global
    data:
      value: "{{ target_temperature }}"
