# =====================================
# AUTOMATIONS HUMIDITÉ - MAEVA
# =====================================

# AUTOMATION 1: Humidité > Seuil (Active boost)
---
alias: Humidité > Seuil - Maeva - On
description: Active boost climatisation si humidité trop haute dans chambre Maeva
mode: single

triggers:
  - entity_id: sensor.th_maeva_humidity
    above: input_number.seuil_humidite_chauffage
    for: "00:02:00"
    trigger: numeric_state

conditions: []

actions:
  - target:
      entity_id: input_boolean.mode_humidite_maeva
    action: input_boolean.turn_on

# =====================================

# AUTOMATION 2: Humidité < Seuil (Désactive boost)
---
alias: Humidité < Seuil - Maeva - Off
description: Désactive boost climatisation si humidité revenue normale dans chambre Maeva
mode: single

triggers:
  - entity_id: sensor.th_maeva_humidity
    below: input_number.seuil_humidite_chauffage
    for: "00:05:00"
    trigger: numeric_state

conditions: []

actions:
  - target:
      entity_id: input_boolean.mode_humidite_maeva
    action: input_boolean.turn_off
