id: activer_remotes_demarrage
alias: Activer remotes au demarrage HA
description: Active tous les remotes Broadlink au demarrage de Home Assistant
mode: single

trigger:
  - platform: homeassistant
    event: start

action:
  # Attendre que HA soit pret
  - delay:
      seconds: 30

  # Activer tous les remotes
  - service: homeassistant.turn_on
    target:
      entity_id:
        - remote.clim_salon
        - remote.clim_maeva
        - remote.clim_axel
