alias: Climatisation - Pilotage Salon
description: Pilotage automatique climatisation Salon avec mode humidite prioritaire - CORRIGE
mode: single

triggers:
  - minutes: /3
    trigger: time_pattern

conditions: []

actions:
  - variables:
      consigne_base: |
        {% if is_state('input_boolean.mode_vacance','on') %}off
        {% else %}
          {% set mode = states('input_select.mode_chauffage_salon') %}
          {% if mode == 'STOP' %}off
          {% elif mode == 'MODEJOUR' %}
            {{ states('sensor.mode_chauffage_global_temperature') | float(18.5) }}
          {% else %}
            {% set temp = mode | regex_findall('\((\d+\.?\d*)\)') %}
            {% if temp | length > 0 %}
              {{ temp | first | float(19) }}
            {% else %}
              19
            {% endif %}
          {% endif %}
        {% endif %}
      boost_humidite: "{{ is_state('input_boolean.mode_humidite_salon', 'on') }}"
      consigne: |
        {% if consigne_base == 'off' %}off
        {% else %}{{ consigne_base | float + (2 if boost_humidite else 0) }}
        {% endif %}
      t_salon: "{{ states('sensor.th_salon_temperature') | float(20) }}"
      etat_actuel: "{{ states('climate.climatisation_salon') }}"

  - service: logbook.log
    data:
      name: "DEBUG CLIM SALON"
      message: "Mode: {{ states('input_select.mode_chauffage_salon') }} | Consigne: {{ consigne }}C | T actuelle: {{ t_salon }}C | Etat: {{ etat_actuel }} | Boost: {{ boost_humidite }}"

  - choose:
      - conditions:
          - "{{ consigne == 'off' }}"
          - "{{ etat_actuel != 'off' }}"
        sequence:
          - service: climate.turn_off
            target:
              entity_id: climate.climatisation_salon
          - service: logbook.log
            data:
              name: "CLIM SALON"
              message: "OFF (consigne=off)"

      - conditions:
          - "{{ consigne != 'off' }}"
          - "{{ (consigne | float - t_salon) >= 0.5 }}"
          - "{{ etat_actuel != 'heat' }}"
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: climate.climatisation_salon
            data:
              temperature: "{{ consigne | float }}"
              hvac_mode: heat
          - service: logbook.log
            data:
              name: "CLIM SALON"
              message: "HEAT {{ consigne }}C (ecart: {{ (consigne | float - t_salon) | round(1) }}C)"

      - conditions:
          - "{{ consigne != 'off' }}"
          - "{{ (consigne | float - t_salon) <= -0.5 }}"
          - "{{ etat_actuel != 'off' }}"
        sequence:
          - service: climate.turn_off
            target:
              entity_id: climate.climatisation_salon
          - service: logbook.log
            data:
              name: "CLIM SALON"
              message: "OFF (T atteinte: {{ t_salon }}C >= {{ consigne }}C)"
