alias: Chauffage - Planning Automatique Horaire
description: Change les modes manuels selon 4 créneaux horaires (toutes pièces)
mode: single

triggers:
  - at: "05:45:00"
    id: confort_matin
    trigger: time
  - at: "08:00:00"
    id: eco_journee
    trigger: time
  - at: "17:00:00"
    id: confort_soir
    trigger: time
  - at: "22:30:00"
    id: horsgel_nuit
    trigger: time

conditions:
  - condition: state
    entity_id: input_boolean.mode_vacance
    state: "off"

actions:
  - variables:
      target_mode: |
        {% if trigger.id in ['confort_matin', 'confort_soir'] %}Confort(19)
        {% elif trigger.id in ['eco_journee', 'horsgel_nuit'] %}Hors-Gel2(17)
        {% else %}Eco(18)
        {% endif %}

  - action: input_select.select_option
    target:
      entity_id:
        - input_select.mode_chauffage_cuisine
        - input_select.mode_chauffage_parents
        - input_select.mode_chauffage_loann
        - input_select.mode_chauffage_salon
        - input_select.mode_chauffage_axel
        - input_select.mode_chauffage_maeva
    data:
      option: "{{ target_mode }}"
