alias: Climatisation - Pilotage Salon
description: Pilotage automatique climatisation Salon - v7 avec turn_on explicite
mode: single

triggers:
  - minutes: /3
    trigger: time_pattern

conditions: []

actions:
  - variables:
      mode_salon: "{{ states('input_select.mode_chauffage_salon') }}"
      mode_vacance: "{{ is_state('input_boolean.mode_vacance','on') }}"
      boost_humidite: "{{ is_state('input_boolean.mode_humidite_salon', 'on') }}"
      t_salon: "{{ states('sensor.th_salon_temperature') | float(20) }}"
      etat_actuel: "{{ states('climate.climatisation_salon') }}"

  - variables:
      consigne_base: >
        {% if mode_vacance %}
          off
        {% elif mode_salon == 'STOP' %}
          off
        {% elif mode_salon == 'MODEJOUR' %}
          {{ states('sensor.mode_chauffage_global_temperature') | float(18.5) }}
        {% else %}
          {% set temp = mode_salon | regex_findall('\((\d+\.?\d*)\)') %}
          {% if temp | length > 0 %}
            {{ temp | first | float(19) }}
          {% else %}
            19
          {% endif %}
        {% endif %}

  - variables:
      consigne: >
        {% if consigne_base | string | trim == 'off' %}
          off
        {% else %}
          {{ consigne_base | float + (2 if boost_humidite else 0) }}
        {% endif %}
      ecart: >
        {% if consigne | string | trim != 'off' %}
          {{ (consigne | float - t_salon) | round(2) }}
        {% else %}
          0
        {% endif %}

  - service: logbook.log
    data:
      name: "DEBUG SALON"
      message: "Mode: {{ mode_salon }} | Consigne: {{ consigne }} | T: {{ t_salon }}C | Ecart: {{ ecart }}C | Etat: {{ etat_actuel }}"

  # CAS 1: Doit etre OFF
  - if:
      - condition: template
        value_template: "{{ consigne | string | trim == 'off' and etat_actuel not in ['off', 'unavailable'] }}"
    then:
      - service: climate.turn_off
        target:
          entity_id: climate.climatisation_salon
      - service: logbook.log
        data:
          name: "SALON"
          message: "-> OFF"

  # CAS 2: Doit chauffer (ecart >= 0.5 ET pas deja en heat)
  - if:
      - condition: template
        value_template: "{{ consigne | string | trim != 'off' and ecart | float >= 0.5 and etat_actuel != 'heat' }}"
    then:
      # D'abord allumer si off
      - if:
          - condition: template
            value_template: "{{ etat_actuel == 'off' }}"
        then:
          - service: climate.turn_on
            target:
              entity_id: climate.climatisation_salon
          - delay:
              seconds: 2
      # Puis regler temperature et mode
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.climatisation_salon
        data:
          hvac_mode: heat
      - delay:
          seconds: 1
      - service: climate.set_temperature
        target:
          entity_id: climate.climatisation_salon
        data:
          temperature: "{{ consigne | float | round(0) }}"
      - service: logbook.log
        data:
          name: "SALON"
          message: "-> HEAT {{ consigne | float | round(0) }}C"

  # CAS 3: Temperature atteinte (ecart <= -0.5 ET en marche)
  - if:
      - condition: template
        value_template: "{{ consigne | string | trim != 'off' and ecart | float <= -0.5 and etat_actuel not in ['off', 'unavailable'] }}"
    then:
      - service: climate.turn_off
        target:
          entity_id: climate.climatisation_salon
      - service: logbook.log
        data:
          name: "SALON"
          message: "-> OFF (T atteinte)"
