- alias: Alerte - Mode Vacances bloque Planning
  description: Alerte si le mode vacances est actif à l'heure du planning chauffage
  trigger:
    - platform: time
      at: "05:45:00"
  condition:
    - condition: state
      entity_id: input_boolean.mode_vacance
      state: "on"
  action:
    - service: persistent_notification.create
      data:
        title: "⚠️ Mode Vacances Actif"
        message: "Le mode vacances est actif - Planning chauffage bloqué!"
  mode: single
