alias: Climatisation - Pilotage Salon
description: Pilotage automatique climatisation Salon - v6 avec debug complet
mode: single

triggers:
  - minutes: /3
    trigger: time_pattern

conditions: []

actions:
  - variables:
      mode_salon: "{{ states('input_select.mode_chauffage_salon') }}"
      mode_vacance: "{{ is_state('input_boolean.mode_vacance','on') }}"
      boost_humidite: "{{ is_state('input_boolean.mode_humidite_salon', 'on') }}"
      t_salon: "{{ states('sensor.th_salon_temperature') | float(20) }}"
      etat_actuel: "{{ states('climate.climatisation_salon') }}"

  - variables:
      consigne_base: >
        {% if mode_vacance %}
          off
        {% elif mode_salon == 'STOP' %}
          off
        {% elif mode_salon == 'MODEJOUR' %}
          {{ states('sensor.mode_chauffage_global_temperature') | float(18.5) }}
        {% else %}
          {% set temp = mode_salon | regex_findall('\((\d+\.?\d*)\)') %}
          {% if temp | length > 0 %}
            {{ temp | first | float(19) }}
          {% else %}
            19
          {% endif %}
        {% endif %}

  - variables:
      consigne: >
        {% if consigne_base | string == 'off' %}
          off
        {% else %}
          {{ consigne_base | float + (2 if boost_humidite else 0) }}
        {% endif %}
      ecart: >
        {% if consigne | string != 'off' %}
          {{ (consigne | float - t_salon) | round(2) }}
        {% else %}
          0
        {% endif %}

  - service: logbook.log
    data:
      name: "DEBUG SALON"
      message: >
        Mode: {{ mode_salon }} |
        Consigne base: {{ consigne_base }} |
        Consigne finale: {{ consigne }} |
        T salon: {{ t_salon }}C |
        Ecart: {{ ecart }}C |
        Etat clim: {{ etat_actuel }} |
        Boost: {{ boost_humidite }}

  # CAS 1: Doit etre OFF
  - if:
      - condition: template
        value_template: "{{ consigne | string == 'off' and etat_actuel != 'off' }}"
    then:
      - service: climate.turn_off
        target:
          entity_id: climate.climatisation_salon
      - service: logbook.log
        data:
          name: "SALON ACTION"
          message: "-> OFF (mode vacance ou STOP)"

  # CAS 2: Doit chauffer (ecart >= 0.5 ET pas deja en heat)
  - if:
      - condition: template
        value_template: "{{ consigne | string != 'off' and ecart | float >= 0.5 and etat_actuel != 'heat' }}"
    then:
      - service: climate.set_temperature
        target:
          entity_id: climate.climatisation_salon
        data:
          temperature: "{{ consigne | float }}"
          hvac_mode: heat
      - service: logbook.log
        data:
          name: "SALON ACTION"
          message: "-> HEAT {{ consigne }}C (ecart: {{ ecart }}C)"

  # CAS 3: Temperature atteinte (ecart < -0.5 ET en marche)
  - if:
      - condition: template
        value_template: "{{ consigne | string != 'off' and ecart | float < -0.5 and etat_actuel != 'off' }}"
    then:
      - service: climate.turn_off
        target:
          entity_id: climate.climatisation_salon
      - service: logbook.log
        data:
          name: "SALON ACTION"
          message: "-> OFF (T atteinte: {{ t_salon }}C >= {{ consigne }}C)"

  # CAS 4: Rien a faire
  - if:
      - condition: template
        value_template: >
          {{
            (consigne | string == 'off' and etat_actuel == 'off') or
            (consigne | string != 'off' and ecart | float >= 0.5 and etat_actuel == 'heat') or
            (consigne | string != 'off' and ecart | float >= -0.5 and ecart | float < 0.5)
          }}
    then:
      - service: logbook.log
        data:
          name: "SALON ACTION"
          message: "-> RIEN (deja dans le bon etat ou zone morte)"
