# =====================================
# AUTOMATIONS HUMIDITÉ - CUISINE
# =====================================

# AUTOMATION 1: Humidité > Seuil (Active boost)
---
alias: Humidité > Seuil - Cuisine - On
description: Active boost chauffage si humidité trop haute dans cuisine
mode: single

triggers:
  - entity_id: sensor.th_cuisine_humidity
    above: input_number.seuil_humidite_chauffage
    for: "00:02:00"
    trigger: numeric_state

conditions: []

actions:
  - target:
      entity_id: input_boolean.mode_humidite_cuisine
    action: input_boolean.turn_on

# =====================================

# AUTOMATION 2: Humidité < Seuil (Désactive boost)
---
alias: Humidité < Seuil - Cuisine - Off
description: Désactive boost chauffage si humidité revenue normale dans cuisine
mode: single

triggers:
  - entity_id: sensor.th_cuisine_humidity
    below: input_number.seuil_humidite_chauffage
    for: "00:05:00"
    trigger: numeric_state

conditions: []

actions:
  - target:
      entity_id: input_boolean.mode_humidite_cuisine
    action: input_boolean.turn_off
