alias: Chauffage - Planning 08:05 Mode Global 19C
description: Remet le mode global a 19C a 08:05 si active
mode: single

triggers:
  - trigger: time
    at: "08:05:00"

conditions:
  - condition: state
    entity_id: input_boolean.planning_0805_actif
    state: "on"
  - condition: state
    entity_id: input_boolean.mode_vacance
    state: "off"

actions:
  - action: input_number.set_value
    target:
      entity_id: input_number.mode_chauffage_global
    data:
      value: 19

  - service: logbook.log
    data:
      name: "PLANNING 08:05"
      message: "Mode Global remis a 19C"
