name: Bug report
description: Report a problem with the heating system
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: ha-version
    attributes:
      label: Home Assistant version
      description: What version of Home Assistant are you running?
      placeholder: e.g. 2024.12.0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear and concise description of the bug
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Paste any relevant logs here (sanitize sensitive data)
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant automation YAML configuration
      render: yaml
